// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2025 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

ul {
  list-style: none;
  margin: 0;
  padding: 0;

  li {
    display: flex;
    align-items: center;
    justify-content: flex-start;
    gap: var(--sys-size-3);
    font: var(--sys-typescale-body4-medium);
    padding-block: var(--sys-size-3);

    span {
      /* push the text down to align slightly better with the icons */
      padding-top: 2px;
    }
  }
}

.check-failed {
  color: var(--app-color-performance-bad);
}

.check-passed {
  color: var(--app-color-performance-good);
}

/*# sourceURL=${import.meta.resolve('./checklist.css')} */`;