// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2024 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

table {
  width: 100%;
  padding: 5px 0;
  border-collapse: collapse;
}

thead {
  white-space: nowrap;
}

table tr > * {
  text-align: right;
}

table tr > *:first-child {
  text-align: left;
}

table.interactive tbody tr {
  cursor: pointer;
}

table.interactive tbody tr:hover,
table.interactive tbody tr.hover,
table.interactive tbody tr.selected {
  background-color: var(--sys-color-state-hover-on-subtle);
}

table thead th {
  font: var(--sys-typescale-body4-medium);
}

table tbody th {
  font-weight: normal;
}

table th[scope='row'] {
  padding: 3px 0;
  word-break: normal;
  overflow-wrap: anywhere;
}

.devtools-link {
  color: var(--sys-color-primary);
  text-decoration: underline;
  cursor: pointer;
  outline-offset: 2px;
  padding: 0;
  margin-left: var(--sys-size-3);
  white-space: nowrap;;
}

button.devtools-link {
  border: none;
  background: none;
  font-family: inherit;
  font-size: inherit;
  height: 16px;
}

/*# sourceURL=${import.meta.resolve('./table.css')} */`;