# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../scripts/build/ninja/devtools_module.gni")
import("../../../scripts/build/typescript/typescript.gni")
import("../visibility.gni")

devtools_module("badges") {
  split_compilation = true
  sources = [
    "AiExplorerBadge.ts",
    "Badge.ts",
    "CodeWhispererBadge.ts",
    "DOMDetectiveBadge.ts",
    "SpeedsterBadge.ts",
    "StarterBadge.ts",
    "UserBadges.ts",
  ]

  ts_deps = [
    "../../core/common:bundle",
    "../../core/host:bundle",
    "../../core/root:bundle",
  ]
}

devtools_entrypoint("bundle") {
  split_compilation = true
  entrypoint = "badges.ts"

  ts_deps = [ ":badges" ]

  visibility = [
    ":*",
    "../../entrypoints/main/*",
    "../../foundation/*",
    "../../panels/*",
    "../../testing/*",
  ]

  visibility += devtools_models_visibility
}

ts_library("unittests") {
  split_compilation = true
  testonly = true

  sources = [
    "AiExplorerBadge.test.ts",
    "Badge.test.ts",
    "UserBadges.test.ts",
  ]

  ts_deps = [
    ":bundle",
    "../../core/common:bundle",
    "../../core/host:bundle",
    "../../core/root:bundle",
    "../../testing",
  ]
}
