# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../scripts/build/ninja/copy.gni")
import("../scripts/build/typescript/typescript.gni")

group("test") {
  testonly = true
  deps = [
    ":api_tests",
    ":run",
    ":unittests",
    "ai_evals",
    "api",
    "e2e",
    "perf",
    "shared",
  ]
}

group("api_tests") {
  testonly = true
  deps = [
    "../front_end:api_test_inputs",
    "../front_end:api_tests",
    "api",
    "api:run_devtools_api_tests",
  ]
}

group("unittests") {
  testonly = true
  deps = [
    "../front_end:test_inputs",
    "../front_end:unittests",
    "../inspector_overlay:unittests",
    "../mcp:foundation_unittests",
    "shared",
    "unit:karma",
    "unit:mocha",
    "unit:run_devtools_node_unit_tests",
    "unit:run_devtools_unit_tests",
  ]
}

node_ts_library("run") {
  sources = [ "run.ts" ]

  inputs = typescript_yargs_types_inputs

  ts_deps = [ "conductor:implementation" ]
}

generated_file("build_config") {
  outputs = [ "$target_gen_dir/build.json" ]
  data = [ "$target_gen_dir/build.json" ]
  output_conversion = "json"
  contents = {
    SOURCE_ROOT = rebase_path("//$devtools_location", target_gen_dir)
    CHECKOUT_ROOT = rebase_path("//", target_gen_dir)
    BUILD_ROOT = rebase_path(root_build_dir, target_gen_dir)
    BUILD_WITH_CHROMIUM = build_with_chromium
  }
}
