# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../scripts/build/ninja/bundle.gni")
import("../scripts/build/ninja/vars.gni")
import("../scripts/build/typescript/typescript.gni")

resources_out_dir = "$root_out_dir/resources/inspector_overlay"

bundle("build_inspector_overlay") {
  entrypoint = "main.ts"
  output_file_location = "$resources_out_dir/main.js"
  bundle_all = true
  format = "iife"
  global_name = "InspectorOverlay"
  css_style_sheet = true
  max_size = 85000
  deps = [
    ":inspector_overlay",
    ":inspector_overlay_sources",
  ]

  public_deps = [ ":copy_resources" ]
}

copy("copy_resources") {
  sources = [ "resources.grd" ]
  outputs = [ "$resources_out_dir/inspector_overlay_resources.grd" ]
}

ts_library("inspector_overlay") {
  sources = [
    "common.ts",
    "css_grid_label_helpers.ts",
    "drag_resize_handler.ts",
    "highlight_common.ts",
    "highlight_container_query.ts",
    "highlight_flex_common.ts",
    "highlight_grid_common.ts",
    "highlight_isolated_element.ts",
    "highlight_scroll_snap.ts",
    "main.ts",
    "tool_green_dev_anchors.ts",
    "tool_highlight.ts",
    "tool_paused.ts",
    "tool_persistent.ts",
    "tool_screenshot.ts",
    "tool_source_order.ts",
    "tool_viewport_size.ts",
    "tool_window_controls.ts",
  ]

  ts_deps = [ "../front_end/core/common:ColorUtils" ]
}

ts_library("unittests") {
  testonly = true

  sources = [
    "common.test.ts",
    "css_grid_label_helpers.test.ts",
    "highlight_common.test.ts",
    "highlight_flex_common.test.ts",
    "highlight_grid_common.test.ts",
    "tool_highlight.test.ts",
    "tool_source_order.test.ts",
    "tool_window_controls.test.ts",
  ]

  ts_deps = [
    ":inspector_overlay",
    "./testing",
  ]
}

generated_file("test_inputs") {
  testonly = true
  outputs = [ "$target_gen_dir/tests.txt" ]
  data_keys = [ "tests" ]
  rebase = target_gen_dir

  deps = [ ":unittests" ]
}
