# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../scripts/build/ninja/devtools_module.gni")
import("../../../scripts/build/typescript/typescript.gni")

devtools_module("crux-manager") {
  split_compilation = true
  sources = [ "CrUXManager.ts" ]

  ts_deps = [
    "../../core/common:bundle",
    "../../core/i18n:bundle",
    "../../core/root:bundle",
    "../../core/sdk:bundle",
    "../emulation:bundle",
  ]
}

devtools_entrypoint("bundle") {
  split_compilation = true
  entrypoint = "crux-manager.ts"

  ts_deps = [ ":crux-manager" ]

  visibility = [
    ":*",
    "../../../mcp/*",
    "../../entrypoints/main",
    "../../foundation/*",
    "../../panels/common/*",
    "../../panels/mobile_throttling/*",
    "../../panels/timeline/*",
    "../../testing/*",
    "../ai_assistance/*",
    "../live-metrics/*",
    "../trace/*",
  ]
}

devtools_foundation_module("foundation_unittests") {
  split_compilation = true
  testonly = true

  sources = [ "CrUXManager.test.ts" ]

  ts_deps = [
    ":bundle",
    "../../core/common:bundle",
    "../../core/platform:bundle",
    "../../core/sdk:bundle",
    "../../testing",
    "../emulation:bundle",
  ]
}
