# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/typescript/typescript.gni")

group("conductor") {
  deps = [
    ":implementation",
    "../../../scripts/hosted_mode",
  ]
}

ts_e2e_library("implementation") {
  testonly = false
  ts_deps = [
    "../../conductor:implementation",
    "../shared",
  ]
  sources = [
    "mocha-interface.ts",
    "mocha_hooks.ts",
    "state-provider.ts",
  ]
}
