// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2015 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  position: absolute;
  inset: 0;
  display: flex;
  background-color: var(--color-background-opacity-80);
  z-index: 1000;
}

.drop-target-message {
  flex: auto;
  font-size: 30px;
  color: var(--sys-color-token-subtle);
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 20px;
  border: 4px dashed var(--sys-color-neutral-outline);
  pointer-events: none;
}

/*# sourceURL=${import.meta.resolve('./dropTarget.css')} */`;