// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2017 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  position: absolute !important; /* stylelint-disable-line declaration-no-important */
  inset: 0;
  overflow: hidden;
  contain: strict;
  background-color: transparent;
}

:host-context(.dimmed-pane) {
  background-color: var(--sys-color-state-scrim);
}

:host-context(.no-pointer-events) {
  pointer-events: none;
}

.widget {
  display: flex;
  background-color: transparent;
  pointer-events: auto;
  flex: none;
}

.no-pointer-events {
  pointer-events: none;
}

/*# sourceURL=${import.meta.resolve('./glassPane.css')} */`;