// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2014 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.progress-indicator-shadow-stop-button {
  background-color: var(--sys-color-error-bright);
  border: 0;
  width: 10px;
  height: 12px;
  border-radius: 2px;
}

.progress-indicator-shadow-container {
  display: flex;
  flex: 1 0 auto;
  align-items: center;
}

.progress-indicator-shadow-container .title {
  text-overflow: ellipsis;
  overflow: hidden;
  max-width: 150px;
  margin-right: 2px;
  color: var(--sys-color-token-subtle);
}

.progress-indicator-shadow-container progress {
  flex: auto;
  margin: 0 2px;
  width: 100px;
}

/*# sourceURL=${import.meta.resolve('./progressIndicator.css')} */`;