// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2017 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.item.disabled {
  opacity: 50%;
}

.item-list {
  background-color: var(--sys-color-cdt-base-container);
  box-shadow: var(--drop-shadow);
  overflow: hidden auto;
  width: 100%;
}

.item.highlighted {
  background-color: var(--sys-color-state-hover-on-subtle);
  outline: var(--sys-size-2) solid var(--sys-color-primary);
  outline-offset: calc(-1 * var(--sys-size-2));
  border-radius: var(--sys-shape-corner-extra-small);
}

@media (forced-colors: active) {
  .item.disabled {
    opacity: 100%;
  }

  .item-list {
    border: var(--sys-size-1) solid ButtonText;
    background-color: ButtonFace;
  }

  .item.highlighted {
    forced-color-adjust: none;
    color: HighlightText;
    background-color: Highlight;
    outline: var(--sys-size-2) solid Highlight;
    outline-offset: calc(-1 * var(--sys-size-2));
    border-radius: var(--sys-shape-corner-extra-small);
  }
}

/*# sourceURL=${import.meta.resolve('./softDropDown.css')} */`;