// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/* Copyright 2026 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file. */

@scope to (devtools-widget > *) {
  :scope {
    flex: none;
  }

  .status-bar {
    display: flex;
    padding: var(--sys-size-4) var(--sys-size-5);
    justify-content: space-between;
    align-items: center;
    border-top: var(--sys-size-1) solid var(--sys-color-divider);
    background: var(--sys-color-cdt-base-container);
  }
}

/*# sourceURL=${import.meta.resolve('./statusBar.css')} */`;