// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2025 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  padding: 0 2px;
  position: relative;
  white-space: nowrap;
  overflow: hidden;
  display: flex;
  flex: none;
  align-items: center;
  z-index: 0;

  --toolbar-height: 26px;
}

:host([floating]) {
  flex-direction: column;
  inset: 0;
  background-color: var(--sys-color-cdt-base-container);
  border: 1px solid var(--sys-color-divider);
  margin-top: -1px;
  width: 28px;
}

:host([hidden]) {
  display: none;
}

:host([wrappable]) {
  flex-wrap: wrap;
  overflow: visible;
}

slot {
  height: var(--toolbar-height);
}

devtools-toolbar-input {
  display: flex;
}

/*# sourceURL=${import.meta.resolve('./toolbar.css')} */`;