# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../../../scripts/build/ninja/devtools_module.gni")
import("../../../../../scripts/build/typescript/typescript.gni")
import("../../../visibility.gni")

devtools_module("graph") {
  split_compilation = true
  sources = [
    "BaseNode.ts",
    "CPUNode.ts",
    "NetworkNode.ts",
    "PageDependencyGraph.ts",
  ]

  ts_deps = [
    "../core:bundle",
    "../types:bundle",
  ]
}

devtools_entrypoint("bundle") {
  split_compilation = true
  entrypoint = "graph.ts"
  ts_deps = [ ":graph" ]
  visibility = [
    ":*",
    "../*",
  ]

  visibility += devtools_models_visibility
}

ts_library("unittests") {
  split_compilation = true
  testonly = true

  sources = [
    "BaseNode.test.ts",
    "PageDependencyGraph.test.ts",
  ]

  ts_deps = [ "../:bundle" ]
}
