import * as Common from '../core/common/common.js';
import * as Host from '../core/host/host.js';
import * as Root from '../core/root/root.js';
import * as SDK from '../core/sdk/sdk.js';
import * as AiAssistance from '../models/ai_assistance/ai_assistance.js';
import * as AutofillManager from '../models/autofill_manager/autofill_manager.js';
import * as Badges from '../models/badges/badges.js';
import * as Bindings from '../models/bindings/bindings.js';
import * as Breakpoints from '../models/breakpoints/breakpoints.js';
import * as CrUXManager from '../models/crux-manager/crux-manager.js';
import * as Emulation from '../models/emulation/emulation.js';
import * as LiveMetrics from '../models/live-metrics/live-metrics.js';
import * as Persistence from '../models/persistence/persistence.js';
import * as ProjectSettings from '../models/project_settings/project_settings.js';
import * as Workspace from '../models/workspace/workspace.js';
import * as WorkspaceDiff from '../models/workspace_diff/workspace_diff.js';
export interface CreationOptions {
    settingsCreationOptions: Omit<Common.Settings.SettingsCreationOptions, 'console'>;
    overrideAutoStartModels?: Set<SDK.SDKModel.SDKModelConstructor>;
    hostConfig: Root.Runtime.HostConfig;
    inspectorFrontendHost: Host.InspectorFrontendHostAPI.InspectorFrontendHostAPI;
    supportsEmulation: boolean;
}
export declare class Universe {
    readonly context: Root.DevToolsContext.DevToolsContext;
    readonly autofillManager: AutofillManager.AutofillManager.AutofillManager;
    readonly supportsEmulation: boolean;
    readonly fileSystemWorkspaceBinding: Persistence.FileSystemWorkspaceBinding.FileSystemWorkspaceBinding;
    constructor(options: CreationOptions);
    get automaticFileSystemManager(): Persistence.AutomaticFileSystemManager.AutomaticFileSystemManager;
    get automaticFileSystemWorkspaceBinding(): Persistence.AutomaticFileSystemWorkspaceBinding.AutomaticFileSystemWorkspaceBinding;
    get aiHistoryStorage(): AiAssistance.AiHistoryStorage.AiHistoryStorage;
    get breakpointManager(): Breakpoints.BreakpointManager.BreakpointManager;
    get cpuThrottlingManager(): SDK.CPUThrottlingManager.CPUThrottlingManager;
    get cruxManager(): CrUXManager.CrUXManager;
    get deviceModeModel(): Emulation.DeviceModeModel.DeviceModeModel | null;
    get domDebuggerManager(): SDK.DOMDebuggerModel.DOMDebuggerManager;
    get domModelUndoStack(): SDK.DOMModel.DOMModelUndoStack;
    get emulatedDevicesList(): Emulation.EmulatedDevices.EmulatedDevicesList;
    get eventBreakpointsManager(): SDK.EventBreakpointsModel.EventBreakpointsManager;
    get fileManager(): Workspace.FileManager.FileManager;
    get gdpClient(): Host.GdpClient.GdpClient;
    get hostConfigTracker(): Host.AidaClient.HostConfigTracker;
    get isolatedFileSystemManager(): Persistence.IsolatedFileSystemManager.IsolatedFileSystemManager;
    get isolateManager(): SDK.IsolateManager.IsolateManager;
    get networkPersistenceManager(): Persistence.NetworkPersistenceManager.NetworkPersistenceManager;
    get networkProjectManager(): Bindings.NetworkProject.NetworkProjectManager;
    get liveMetrics(): LiveMetrics.LiveMetrics;
    get frameManager(): SDK.FrameManager.FrameManager;
    get pageResourceLoader(): SDK.PageResourceLoader.PageResourceLoader;
    get persistence(): Persistence.Persistence.PersistenceImpl;
    get projectSettingsModel(): ProjectSettings.ProjectSettingsModel.ProjectSettingsModel;
    get settings(): Common.Settings.Settings;
    get targetManager(): SDK.TargetManager.TargetManager;
    get userBadges(): Badges.UserBadges;
    get workspace(): Workspace.Workspace.WorkspaceImpl;
    get workspaceDiff(): WorkspaceDiff.WorkspaceDiff.WorkspaceDiffImpl;
}
