// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2023 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  height: 100%;
}

.placeholder {
  display: flex;
  height: 100%;
}

.ruleset-header-container {
  flex-shrink: 0;
}

.ruleset-header {
  padding: var(--sys-size-3) var(--sys-size-5);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  border-bottom: var(--sys-size-1) solid var(--sys-color-divider);
}

.ruleset-header devtools-icon {
  vertical-align: sub;
}

.text-editor-container {
  overflow: auto;
}

/*# sourceURL=${import.meta.resolve('./RuleSetDetailsView.css')} */`;