// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2019 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

 devtools-data-grid {
  flex: auto;
}

.cookies-table devtools-icon {
  margin-right: 4px;
}

/*# sourceURL=${import.meta.resolve('./cookiesTable.css')} */`;