# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../scripts/build/ninja/devtools_module.gni")
import("../../../scripts/build/ninja/devtools_worker.gni")
import("../../../scripts/build/typescript/typescript.gni")
import("../visibility.gni")

devtools_module("wasmparser_worker") {
  split_compilation = true
  sources = [ "WasmParserWorker.ts" ]

  ts_deps = [
    "../../core/common:bundle",
    "../../third_party/wasmparser:bundle",
  ]
}

devtools_entrypoint("bundle") {
  split_compilation = true
  entrypoint = "wasmparser_worker.ts"

  ts_deps = [ ":wasmparser_worker" ]

  visibility = [ ":*" ]

  visibility += devtools_entrypoints_visibility
}

devtools_entrypoint("worker_entrypoint") {
  split_compilation = true
  entrypoint = "wasmparser_worker-entrypoint.ts"

  forward_variables_from(devtools_worker_config, "*")

  ts_deps = [ ":bundle" ]

  visibility = [ "../../../front_end" ]

  visibility += devtools_entrypoints_visibility
}

ts_library("unittests") {
  split_compilation = true
  testonly = true

  sources = [ "wasmparser_worker.test.ts" ]

  ts_deps = [
    ":bundle",
    "../../testing",
  ]
}
