# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../scripts/build/ninja/devtools_module.gni")
import("../../../scripts/build/ninja/generate_css.gni")
import("../../../scripts/build/typescript/typescript.gni")
import("../visibility.gni")

generate_css("css_files") {
  sources = [
    "searchResultsPane.css",
    "searchView.css",
  ]
}

devtools_ui_module("search") {
  split_compilation = true
  sources = [
    "SearchResultsPane.ts",
    "SearchScope.ts",
    "SearchView.ts",
  ]

  deps = [ ":css_files" ]

  ts_deps = [
    "../../core/common:bundle",
    "../../core/host:bundle",
    "../../core/i18n:bundle",
    "../../core/platform:bundle",
    "../../core/text_utils:bundle",
    "../../models/workspace:bundle",
    "../../ui/components/buttons:bundle",
    "../../ui/kit:bundle",
    "../../ui/legacy:bundle",
    "../../ui/lit:bundle",
    "../../ui/visual_logging:bundle",
  ]
}

devtools_entrypoint("bundle") {
  split_compilation = true
  entrypoint = "search.ts"

  deps = [ ":css_files" ]

  ts_deps = [ ":search" ]

  visibility = [
    ":*",
    "../../entrypoints/*",
    "../network/*",
    "../sources/*",
  ]

  visibility += devtools_panels_visibility
}

devtools_ui_module("unittests") {
  split_compilation = true
  testonly = true

  sources = [
    "SearchResultsPane.test.ts",
    "SearchView.test.ts",
  ]

  ts_deps = [
    ":bundle",
    "../../core/common:bundle",
    "../../core/text_utils:bundle",
    "../../models/workspace:bundle",
    "../../testing",
    "../../ui/legacy:bundle",
  ]
}
