# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../scripts/build/ninja/devtools_module.gni")
import("../../../scripts/build/ninja/devtools_worker.gni")
import("../../../scripts/build/typescript/typescript_vars.gni")

devtools_module("lighthouse_worker") {
  sources = [ "LighthouseWorkerService.ts" ]

  # lighthouse_worker runs in the browser, but it adapts Lighthouse and
  # Puppeteer which rely on globalThis.global (LighthouseWorkerService.ts) and
  # Node types referenced by Puppeteer's declarations. Under remote execution
  # (-strict_remote), these type definitions must be explicitly provided in
  # inputs.
  inputs = typescript_node_types_inputs

  ts_deps = [
    "../../core/protocol_client:bundle",
    "../../core/root:bundle",
    "../../services/puppeteer:bundle",
    "../../third_party/third-party-web:bundle",
  ]
}

devtools_entrypoint("bundle") {
  entrypoint = "lighthouse_worker.ts"

  forward_variables_from(devtools_worker_config, "*")

  deps = [ "../../third_party/lighthouse" ]
  ts_deps = [ ":lighthouse_worker" ]

  visibility = [ "../..:front_end" ]
}
