# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../scripts/build/ninja/devtools_module.gni")
import("../../../scripts/build/ninja/devtools_worker.gni")

devtools_module("lighthouse_worker") {
  split_compilation = true
  sources = [ "LighthouseWorkerService.ts" ]

  ts_deps = [
    "../../core/protocol_client:bundle",
    "../../core/root:bundle",
    "../../services/puppeteer:bundle",
    "../../third_party/third-party-web:bundle",
  ]
}

devtools_entrypoint("bundle") {
  split_compilation = true
  entrypoint = "lighthouse_worker.ts"

  forward_variables_from(devtools_worker_config, "*")

  deps = [ "../../third_party/lighthouse" ]
  ts_deps = [ ":lighthouse_worker" ]

  visibility = [ "../..:front_end" ]
}
