// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2024 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  padding: var(--sys-size-2) var(--sys-size-1) var(--sys-size-2) var(--sys-size-2);
}

.title {
  padding-left: var(--sys-size-5);
}

.subtitle {
  padding-left: var(--sys-size-5);
}

/*# sourceURL=${import.meta.resolve('./preloading/preloadingViewDropDown.css')} */`;