# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../scripts/build/typescript/typescript.gni")

devtools_entrypoint("bundle") {
  split_compilation = true
  entrypoint = "i18n.ts"

  ts_deps = [
    "../../core/i18n:bundle",
    "../../third_party/i18n:bundle",
    "../../ui/lit:bundle",
  ]

  visibility = [
    ":*",
    "../../entrypoints/*",
    "../../panels/*",
    "../../ui/*",
  ]
}

ts_library("unittests") {
  testonly = true
  split_compilation = true

  sources = [ "i18n.test.ts" ]

  ts_deps = [
    ":bundle",
    "../../core/i18n:bundle",
    "../../third_party/i18n:bundle",
  ]
}
