# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../config/gni/devtools_image_files.gni")
import("../../scripts/build/ninja/devtools_pre_built.gni")
import("../../scripts/build/ninja/node.gni")
import("../../scripts/build/ninja/vars.gni")

devtools_pre_built("Images") {
  sources = devtools_image_files
}

node_action("optimize_images") {
  script = "scripts/build/optimize_images.js"

  _output_file_location = target_gen_dir + "/Images.js"

  _svg_sources = []
  foreach(svg_image, devtools_svg_sources) {
    _svg_sources += [ "src/$svg_image" ]
  }

  inputs = [ devtools_location_prepend + "node_modules/svgo/package.json" ] +
           _svg_sources + devtools_image_files

  public_deps = [ ":Images" ]

  response_file_contents = [ "--svgs" ]
  response_file_contents += rebase_path(_svg_sources, root_build_dir)
  response_file_contents += [ "--images" ]
  response_file_contents += devtools_image_files

  args = [
    "--target-gen-dir",
    rebase_path(target_gen_dir, root_build_dir),
    "--file-list",
    "{{response_file_name}}",
  ]

  _grd_files = [ _output_file_location ]
  foreach(svg_image, devtools_svg_sources) {
    _grd_files += [ "$target_gen_dir/$svg_image" ]
  }

  outputs = _grd_files
  data = outputs

  metadata = {
    grd_files = _grd_files
    foreach(_image_file, devtools_image_files) {
      grd_files += [ "$target_gen_dir/$_image_file" ]
    }
  }
}
