# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../scripts/build/ninja/copy.gni")
import("../../scripts/build/typescript/typescript.gni")

group("perf") {
  testonly = true
  deps = [
    ":test_inputs",
    ":tests",
  ]
}

node_ts_library("tests") {
  split_compilation = true
  sources = [ "run-mocha.ts" ]

  ts_deps = [
    "../conductor:implementation",
    "../e2e/conductor:implementation",
    "../shared",
  ]

  deps = [
    "application",
    "helpers",
    "panels/performance",
    "report",
    "setup",
  ]
}

generated_file("test_inputs") {
  testonly = true
  outputs = [ "$target_gen_dir/tests.txt" ]
  data_keys = [ "tests" ]
  rebase = target_gen_dir

  deps = [ ":tests" ]
}
