#!/usr/bin/env python3
#
# Copyright 2020 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import argparse
import json
import os
import sys

substitutions = {
    "lit_inputs":
        os.path.dirname(os.path.abspath(__file__)),
    "unit_inputs":
        os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "../../../unittests/Inputs")
}

parser = argparse.ArgumentParser()
parser.add_argument("input", type=argparse.FileType())
options = parser.parse_args()

text = [
    l % substitutions
    for l in options.input.readlines()
    if not l.strip().startswith("#")
]

inputs = json.loads('\n'.join(text))

for I in inputs:
  I["jsonrpc"] = "2.0"
  I["id"] = 0
  output = json.dumps(I)
  sys.stdout.write("Content-Length: %d\n\n%s" % (len(output), output))
