# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../../scripts/build/ninja/bundle.gni")
import("../../../../scripts/build/ninja/devtools_module.gni")
import("../../../../scripts/build/typescript/typescript.gni")

recorder_injected_sources = [
  "Logger.ts",
  "MonotonicArray.ts",
  "RecordingClient.ts",
  "SelectorComputer.ts",
  "SelectorPicker.ts",
  "Step.ts",
  "injected.ts",
  "selectors/ARIASelector.ts",
  "selectors/CSSSelector.ts",
  "selectors/PierceSelector.ts",
  "selectors/Selector.ts",
  "selectors/TextSelector.ts",
  "selectors/XPath.ts",
  "util.ts",
]

devtools_module("injected") {
  sources = recorder_injected_sources

  ts_deps = [
    "../../../third_party/puppeteer",
    "../../../third_party/puppeteer:bundle",
    "../../../third_party/puppeteer-replay:bundle",
  ]

  visibility = [
    ":*",
    "../:*",
    "../models:*",
    "selectors:*",
  ]
}

bundle("bundled_library") {
  entrypoint = "injected.ts"
  output_file_location = "$target_gen_dir/injected.generated.js"
  bundle_all = true
  format = "iife"
  sourcemap = false
  deps = [
    ":injected_sources",
    "../../../third_party/puppeteer",
    "../../../third_party/puppeteer:bundle",
    "../../../third_party/puppeteer-replay:bundle",
  ]

  data = [ output_file_location ]
  metadata = {
    grd_files = [ output_file_location ]
  }

  visibility = [
    ":*",
    "../:*",
    "../models:*",
  ]
}
