# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../../scripts/build/ninja/devtools_module.gni")
import("../../../../scripts/build/ninja/node.gni")
import("../../../../scripts/build/typescript/typescript.gni")

recorder_injected_sources = [
  "Logger.ts",
  "MonotonicArray.ts",
  "RecordingClient.ts",
  "SelectorComputer.ts",
  "SelectorPicker.ts",
  "Step.ts",
  "injected.ts",
  "selectors/ARIASelector.ts",
  "selectors/CSSSelector.ts",
  "selectors/PierceSelector.ts",
  "selectors/Selector.ts",
  "selectors/TextSelector.ts",
  "selectors/XPath.ts",
  "util.ts",
]

devtools_module("injected") {
  sources = recorder_injected_sources

  ts_deps = [
    "../../../third_party/puppeteer",
    "../../../third_party/puppeteer:bundle",
    "../../../third_party/puppeteer-replay:bundle",
  ]

  visibility = [
    ":*",
    "../:*",
    "../models:*",
    "selectors:*",
  ]
}

node_action("bundled_library") {
  script = "node_modules/rollup/dist/bin/rollup"

  _bundled_entrypoint = target_gen_dir + "/injected.js"
  _output_file_location = target_gen_dir + "/injected.generated.js"

  inputs = [
             _bundled_entrypoint,
             "rollup.config.mjs",
           ] + recorder_injected_sources

  deps = [ ":injected_checked" ]

  args = [
    "--config",
    rebase_path("rollup.config.mjs", root_build_dir),
    "--input",
    rebase_path(_bundled_entrypoint, root_build_dir),
    "--file",
    rebase_path(_output_file_location, root_build_dir),
  ]

  if (is_debug) {
    args += [ "--environment=DEBUG_INJECTED" ]
  }

  outputs = [ _output_file_location ]
  data = outputs
  metadata = {
    grd_files = [ _output_file_location ]
  }

  visibility = [
    ":*",
    "../:*",
    "../models:*",
  ]
}
