// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2014 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.font-view {
  font-size: 60px;
  white-space: pre-wrap;
  overflow-wrap: break-word;
  text-align: center;
  padding: 15px;
}

/*# sourceURL=${import.meta.resolve('./fontView.css')} */`;