// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2023 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.menu-item {
  padding: var(--sys-size-3) 0 var(--sys-size-3) var(--sys-size-9);
  font-size: 12px;
  line-height: 16px;
  position: relative;
  display: block;
  color: var(--sys-color-on-surface);
}

.menu-item:focus {
  outline: none;
}

:host(.no-checkmark) .menu-item {
  padding-left: 0;
}

:host(:not(:first-child)) .menu-item {
  border-top: var(--override-divider-line);
}

:host-context(devtools-menu-group) .menu-item {
  padding: var(--sys-size-3) 0 var(--sys-size-3) var(--sys-size-9);
}

.is-selected-item::before {
  content: "";
  position: absolute;
  left: var(--sys-size-2);
  top: 50%;
  transform: translateY(-50%);
  display: inline-block;
  mask-repeat: no-repeat;
  mask-position: center;
  width: calc(var(--menu-checkmark-width) - 10px);
  height: var(--menu-checkmark-height);
  mask-image: var(--selected-item-check);
  background: var(--sys-color-token-subtle);
}

.is-disabled-item {
  opacity: 60%;
}

:host(:hover:not(.prevents-close)) .menu-item::after,
:host(:focus-visible:not(.prevents-close)) .menu-item::after {
  content: "";
  height: 100%;
  width: calc(100% + 2* var(--sys-size-8));
  border-radius: inherit;
  position: absolute;
  top: 0;
  left: calc(-1 * var(--sys-size-8));
  background-color: var(--sys-color-state-hover-on-subtle);
}

:host(:focus) {
  outline: none;
}

/*# sourceURL=${import.meta.resolve('./menuItem.css')} */`;