// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/**
 * Copyright 2025 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.overlay {
  position: absolute;
  z-index: 1000;
  display: flex;
  flex-direction: column;
  align-items: center;

  /* From the other bubble */
  background-color: var(--color-background-inverted);
  color: var(--color-background);
  pointer-events: auto;
  border-radius: var(--sys-shape-corner-extra-small);
  white-space: pre-wrap;
  max-width: 300px;
  width: max-content;
  padding: var(--sys-size-3) var(--sys-size-4);
  font-family: var(--default-font-family);
  font-size: var(--sys-typescale-body2-size);
  font-weight: var(--ref-typeface-weight-medium);
  outline: 2px solid var(--color-background);
}

.connectorContainer {
  z-index: 1000;
  overflow: visible;
  pointer-events: none;
}

.close-button {
  position: absolute;
  top:1px;
  z-index: 1000;
  cursor: pointer;
}

/*# sourceURL=${import.meta.resolve('./annotation.css')} */`;