// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2026 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

@scope to (devtools-widget > *) {
  .pill-container {
    display: flex;
    align-items: center;
    gap: var(--sys-size-3);
  }
}

/*# sourceURL=${import.meta.resolve('./commentsStatusBarPill.css')} */`;