// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2026 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

@scope to (devtools-widget > *) {
  .comment-thread-widget {
    display: flex;
    width: var(--sys-size-30);
    padding: var(--sys-size-8);
    flex-direction: column;
    align-items: flex-start;
    gap: var(--sys-size-4);
    border-radius: var(--sys-shape-corner-medium);
    background: var(--sys-color-base);
    box-shadow: var(--sys-elevation-level2);
    cursor: default;
  }

  .comment-thread-widget.submitted {
    background: var(--sys-color-surface2);
  }

  .header {
    display: flex;
    width: 100%;
    justify-content: space-between;
    align-items: center;
  }

  .sent-status {
    display: flex;
    align-items: center;
    gap: var(--sys-size-2);
    font-size: var(--sys-typescale-body5-size);
    color: var(--sys-color-on-surface-subtle);
  }

  .check-icon {
    width: var(--sys-size-7);
    height: var(--sys-size-7);
    color: var(--sys-color-on-surface-subtle);
  }

  .selected-item {
    display: flex;
    height: calc(var(--sys-size-8) + var(--sys-size-2));
    padding: var(--sys-size-2) var(--sys-size-4) var(--sys-size-2) var(--sys-size-3);
    align-items: center;
    border-radius: var(--sys-shape-corner-extra-small);
    border: var(--sys-size-1) solid var(--sys-color-divider);
    background: var(--sys-color-base);
    font-family: var(--source-code-font-family);
    font-size: var(--monospace-font-size);
    color: var(--sys-color-token-tag);
    overflow: hidden;
    max-width: 100%;
    min-width: 0;
  }

  .comment-text {
    width: 100%;
    font-family: var(--default-font-family);
    font-size: var(--sys-typescale-body4-size);
    color: var(--sys-color-on-surface-subtle);
    line-height: var(--sys-size-9);
    overflow-wrap: break-word;
    white-space: pre-wrap;
  }

  .agent-response {
    display: flex;
    gap: var(--sys-size-2);
    margin-top: var(--sys-size-4);
    width: 100%;
    align-items: flex-start;
  }

  .elbow {
    width: var(--sys-size-6);
    height: var(--sys-size-6);
    margin-left: var(--sys-size-3);
    margin-right: var(--sys-size-3);
    border-left: var(--sys-size-1) solid var(--sys-color-neutral-outline);
    border-bottom: var(--sys-size-1) solid var(--sys-color-neutral-outline);
    border-bottom-left-radius: var(--sys-size-6);
    flex-shrink: 0;
  }

  .response-content {
    display: flex;
    flex-direction: column;
    flex: 1;
    min-width: 0;

    --code-block-background-color: var(--sys-color-base);
    --code-background-color: var(--sys-color-base);
  }

  .response-header {
    font-weight: bold;
    margin-bottom: var(--sys-size-2);
    font-family: var(--default-font-family);
    font-size: var(--sys-typescale-body5-size);
    line-height: var(--sys-size-8);
    color: var(--sys-color-on-surface-subtle);
  }

  .response-content devtools-markdown-view {
    font-family: var(--default-font-family);
    font-size: var(--sys-typescale-body4-size);
    color: var(--sys-color-on-surface-subtle);
    line-height: var(--sys-size-9);
  }

  .input {
    height: auto;
    min-height: var(--sys-size-14);
    max-height: var(--sys-size-27);
    field-sizing: content;
    resize: none;
    scrollbar-width: none;
    padding: var(--sys-size-5) var(--sys-size-8);
    border-radius: var(--sys-shape-corner-small);
    border: var(--sys-size-1) solid var(--sys-color-outline);
    background: var(--sys-color-base);
    font-family: var(--default-font-family);
    font-size: var(--sys-typescale-body5-size);
    line-height: var(--sys-size-9);
    letter-spacing: 0;
  }

  .input::placeholder {
    color: var(--sys-color-on-surface-subtle);
  }

  .footer {
    display: flex;
    width: 100%;
    justify-content: flex-end;
    align-items: center;
    gap: var(--sys-size-5);
  }

  .info-icon {
    color: var(--sys-color-on-surface-subtle);
    cursor: pointer;
  }

  .info-tooltip-container {
    max-width: var(--sys-size-28);
    padding: var(--sys-size-4) var(--sys-size-5);
  }

  .selected-item-text {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }
}

/*# sourceURL=${import.meta.resolve('./commentThreadWidget.css')} */`;