// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2015 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.timeline-status-dialog {
  display: flex;
  flex-direction: column;
  padding: var(--sys-size-8) var(--sys-size-8) var(--sys-size-6);
  align-self: center;
  background-color: var(--sys-color-cdt-base-container);
  box-shadow: var(--drop-shadow);
  border-radius: 10px;
}

.status-dialog-line {
  margin: var(--sys-size-2);
  height: var(--sys-size-7);
  min-height: auto;
  display: flex;
  align-items: baseline;
  font-variant-numeric: tabular-nums;
}

.status-dialog-line .label {
  display: inline-block;
  width: var(--sys-size-19);
  text-align: right;
  color: var(--sys-color-on-surface);
  margin-right: 10px;
}

.timeline-status-dialog .progress .indicator-container {
  display: inline-block;
  width: 200px;
  height: var(--sys-size-5);
  background-color: var(--sys-color-surface5);
}

.timeline-status-dialog .progress .indicator {
  background-color: var(--sys-color-primary);
  height: 100%;
  width: 0;
  margin: 0;
}

.timeline-status-dialog .stop-button {
  margin-top: var(--sys-size-5);
  height: 100%;
  align-self: flex-end;
}

.timeline-status-dialog .stop-button button {
  border-radius: var(--sys-shape-corner-medium-small);
}

@media (forced-colors: active) {
  .timeline-status-dialog {
    border: var(--sys-size-1) solid canvastext;
  }

  .timeline-status-dialog .progress .indicator-container {
    border: var(--sys-size-1) solid ButtonText;
    background-color: ButtonFace;
  }

  .timeline-status-dialog .progress .indicator {
    forced-color-adjust: none;
    background-color: ButtonText;
  }
}

:host {
  container-type: inline-size;
}

/* 326 is the widths above (200 + 80) + a bunch of padding. calc() can't be used here sadly */
@container (max-width: 326px) {
  .timeline-status-dialog {
    box-shadow: none;

    .stop-button {
      align-self: center;
    }
  }

  .status-dialog-line {
    flex-direction: column;

    .label {
      display: none;
    }
  }
}

/*# sourceURL=${import.meta.resolve('./timelineStatusDialog.css')} */`;