// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2023 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  display: block;
}

.breakdown {
  margin: 0;
  padding: 0;
  list-style: none;
  color: var(--sys-color-token-subtle);
}

.value {
  display: inline-block;
  padding: 0 5px;
  color: var(--sys-color-on-surface);
}

/*# sourceURL=${import.meta.resolve('./interactionBreakdown.css')} */`;