// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/* Copyright 2026 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file. */

:host {
  display: flex;
}

.container {
  display: flex;
  width: 100%;
  height: 150px;
  background-color: var(--sys-color-cdt-base-container);
  border-radius: 8px;
  border: 1px solid var(--sys-color-divider);
}

.container canvas {
  /* stylelint-disable-next-line declaration-no-important */
  pointer-events: none !important;
}

.flex-auto {
  flex: auto;
}

.vbox {
  display: flex;
  flex-direction: column;
  position: relative;
}

/*# sourceURL=${import.meta.resolve('./networkTrackWidget.css')} */`;