// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2024 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.origin-warning-icon {
  width: var(--sys-size-8);
  height: var(--sys-size-8);
  margin-right: var(--sys-size-3);
  color: var(--icon-warning);
}

.origin {
  text-overflow: ellipsis;
  overflow-x: hidden;
}

.error-message {
  color: var(--sys-color-error);
  margin-top: var(--sys-size-5);
  font-weight: var(--ref-typeface-weight-medium);
  white-space: pre-wrap;
}

/*# sourceURL=${import.meta.resolve('./originMap.css')} */`;