// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2024 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  display: block;
  padding: 5px 8px;
}

.passed-insights-section {
  margin-top: var(--sys-size-5);

  summary {
    font-weight: var(--ref-typeface-weight-medium);
  }
}

/*# sourceURL=${import.meta.resolve('./sidebarSingleInsightSet.css')} */`;