// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/linear_memory_inspector/LinearMemoryInspector.ts
*/

import './LinearMemoryInspector.js';
/**
* @typedef {{
* memory:!Uint8Array,
* address:number,
* }}
*/
// @ts-ignore we export this for Closure not TS
export let LinearMemoryInspectorData;
// eslint-disable-next-line no-unused-vars
export class LinearMemoryInspectorClosureInterface extends HTMLElement {
  /**
  * @param {!LinearMemoryInspectorData} data
  */
  set data(data) {
  }
}
/**
* @return {!LinearMemoryInspectorClosureInterface}
*/
export function createLinearMemoryInspector() {
  return /** @type {!LinearMemoryInspectorClosureInterface} */ (
      document.createElement('devtools-linear-memory-inspector-inspector'));
}
