// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2015 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  display: inline-flex;
}

.custom-expandable-section {
  display: inline-flex;
  flex-direction: column;
}

.custom-expand-icon {
  user-select: none;
  margin-right: var(--sys-size-3);
  margin-bottom: calc(-1 * var(--sys-size-3));
}

.custom-expandable-section-standard-section {
  display: inline-flex;
}

.custom-expandable-section-default-body {
  padding-left: var(--sys-size-6);
}

/*# sourceURL=${import.meta.resolve('./customPreviewComponent.css')} */`;