// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2021 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  padding: 0;
  margin: 0;
}

input {
  height: var(--sys-size-6);
  width: var(--sys-size-6);
  min-height: var(--sys-size-6);
  min-width: var(--sys-size-6);
  margin: var(--sys-size-4);
}

label {
  display: inline-flex;
  align-items: center;
  overflow: hidden;
  text-overflow: ellipsis;
}

p {
  margin: var(--sys-size-4) 0;
}

.info-icon {
  cursor: pointer;
  position: relative;
  margin-left: var(--sys-size-2);
  top: var(--sys-size-2);
  width: var(--sys-size-9);
  height: var(--sys-size-9);
}

.link {
  color: var(--text-link);
  text-decoration: underline;
}

/*# sourceURL=${import.meta.resolve('./settingCheckbox.css')} */`;