// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2022 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.clickable {
  cursor: pointer;
}

devtools-icon {
  vertical-align: text-bottom;
  padding-left: 2px;
}

/*# sourceURL=${import.meta.resolve('./settingDeprecationWarning.css')} */`;