# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../../scripts/build/ninja/copy.gni")

copy_to_gen("memory") {
  sources = [
    "allocations.html",
    "attached-iframe.html",
    "context-analysis/async.js",
    "context-analysis/block-variable-inner.js",
    "context-analysis/block-variable.js",
    "context-analysis/block.js",
    "context-analysis/captured-this.js",
    "context-analysis/catch-parameter.js",
    "context-analysis/catch.js",
    "context-analysis/class-direct.js",
    "context-analysis/class-initializer-context.js",
    "context-analysis/class-methods.js",
    "context-analysis/class.js",
    "context-analysis/context.js",
    "context-analysis/dead-closure.js",
    "context-analysis/direct-eval.js",
    "context-analysis/for-of.js",
    "context-analysis/generator.js",
    "context-analysis/index.html",
    "context-analysis/inside-direct-eval.js",
    "context-analysis/module.js",
    "context-analysis/nested.js",
    "context-analysis/parameter.js",
    "context-analysis/script.js",
    "context-analysis/shadowed.js",
    "context-analysis/uninstantiated-inner.js",
    "context-analysis/with.js",
    "default.html",
    "detached-dom-tree.html",
    "detached-iframe.html",
    "detached-node.html",
    "diff.html",
    "dom-details.html",
    "dom-objects.html",
    "duplicated-names.html",
    "event-listeners.html",
    "filtering.html",
    "ignoring-retainers.html",
    "multiple-retainers.html",
    "set.html",
    "weakmap.html",
  ]
}
