// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2021 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  padding: var(--sys-size-9);
  height: 100%;
  display: flex;
}

.heading {
  font-size: 15px;
}

devtools-data-grid {
  margin-top: var(--sys-size-9);

  & devtools-button {
    width: var(--sys-size-7);
    height: var(--sys-size-7);
  }
}

devtools-icon {
  width: var(--sys-size-7);
  height: var(--sys-size-7);
}

.no-tt-message {
  margin-top: var(--sys-size-9);
}

/*# sourceURL=${import.meta.resolve('./trustTokensView.css')} */`;