// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2015 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

@scope to (devtools-widget > *) {
  .excluded-folder-header {
    display: flex;
    flex-direction: column;
    min-height: var(--sys-size-16);
    padding: var(--sys-size-4) var(--sys-size-6);
    gap: var(--sys-size-4);

    & > .excluded-folder-url {
      color: var(--sys-color-on-surface-subtle);
      overflow-wrap: break-word;
    }
  }

  .exclude-subfolders-table {
    padding: var(--sys-size-4) 0;
  }

  .excluded-folder-error {
    color: var(--sys-color-error);
  }
}

/*# sourceURL=${import.meta.resolve('./editFileSystemView.css')} */`;