// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2015 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.ignore-list-option {
  flex: none;
  display: flex;
  align-items: center;
  height: var(--sys-size-13);
}

.ignore-list-option devtools-button {
  cursor: pointer;
  position: relative;
  top: var(--sys-size-2);
  margin-left: var(--sys-size-2);
}

.add-button {
  padding: var(--sys-size-5) var(--sys-size-6);
  align-self: flex-start;
  flex: none;
}

.ignore-list {
  flex: 0 1 auto;
}

.enable-ignore-listing,
.ignore-list-item,
.general-exclusion-group {
  padding-left: var(--sys-size-4);
}

.custom-exclusion-group {
  padding-left: 0;
  padding-right: 0;
}

.ignore-list-item {
  height: var(--sys-size-13);
  display: flex;
  align-items: center;
  position: relative;
  flex: auto 1 1;
}

.ignore-list-pattern {
  flex: auto;
}

.ignore-list-item > devtools-checkbox {
  width: 100%;
}

.ignore-list-item .ignore-list-pattern {
  white-space: nowrap;
  text-overflow: ellipsis;
  user-select: none;
  color: var(--sys-color-on-surface);
  overflow: hidden;
}

.ignore-list-edit-row {
  flex: none;
  display: flex;
  flex-direction: row;
  margin: 6px 5px;
  align-items: center;
}

.ignore-list-edit-row input,
.ignore-list-edit-row select {
  width: 100%;
  text-align: inherit;
}

.list:has(.ignore-list-empty),
.list:has(.ignore-list-edit-row),
.list:has(.ignore-list-item) {
  border: none;
}

.editor-container:has(.ignore-list-edit-row) {
  background: var(--sys-color-surface1);
  border-radius: 10px;
}

.ignore-list.list-editing ~ .add-button {
  display: none;
}

.devtools-link:has(devtools-icon) {
  margin-left: 6px;
}

/*# sourceURL=${import.meta.resolve('./frameworkIgnoreListSettingsTab.css')} */`;