// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/elements/ElementsBreadcrumbs.ts
*/

import './ElementsBreadcrumbs.js';
/**
* @typedef {{
* selectedNode:?DOMNode,
* crumbs:!Array.<!DOMNode>,
* }}
*/
// @ts-ignore we export this for Closure not TS
export let ElementsBreadcrumbsData;
/**
* @typedef {{
* parentNode:(!DOMNode|undefined),
* id:number,
* nodeType:number,
* pseudoType:(string|undefined),
* shadowRootType:?string,
* nodeName:string,
* nodeNameNicelyCased:string,
* legacyDomNode:*,
* highlightNode:function():void,
* clearHighlight:function():void,
* getAttribute:function(string):(string|undefined),
* }}
*/
// @ts-ignore we export this for Closure not TS
export let DOMNode;
// eslint-disable-next-line no-unused-vars
export class ElementsBreadcrumbsClosureInterface extends HTMLElement {
  /**
  * @param {!ElementsBreadcrumbsData} data
  */
  set data(data) {
  }
}
/**
* @return {!ElementsBreadcrumbsClosureInterface}
*/
export function createElementsBreadcrumbs() {
  return /** @type {!ElementsBreadcrumbsClosureInterface} */ (document.createElement('devtools-elements-breadcrumbs'));
}
