# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../../scripts/build/ninja/devtools_module.gni")

devtools_ui_module("extensions") {
  split_compilation = true
  sources = [ "ExtensionManager.ts" ]
  ts_deps = [
    "../../../core/common:bundle",
    "../../../models/extensions:bundle",
    "../../../panels/common:bundle",
  ]

  public_deps = []
}

devtools_entrypoint("bundle") {
  split_compilation = true
  entrypoint = "extensions.ts"
  ts_deps = [ ":extensions" ]

  visibility = [
    ":*",
    "../:*",
    "../../../ui/components/docs/*",
    "../components:*",
    "../converters:*",
  ]
}
