description = "Migrates a test file to the e2e_non_hosted folder"
prompt = """
# Task: Migrates a test file to the e2e_non_hosted format.

**The user's raw command is appended below your instructions.**

Your task is to parse the `<original_test_file>`, `<target_test_file>`, and `<issue_id>` from their input
and migrate `<original_test_file>` to the `<target_test_file>`.

## Expected Format
The command follows this format: `/migrate-e2e-non-hosted <original_test_file> <target_test_file> <issue_id>`

## Step-by-step instructions

Step by step instructions:

1) Read all tests in @<target_test_file> as examples to understand the aspects of the already migrated files.
2) Read all files in @test/e2e_non_hosted/shared.
3) Read the non-migrated test file @<original_test_file>.
4) Read relevant helpers files imported from the test file.
5) Create an empty file for the migrated test @<target_test_file>.
6) Update BUILD.gn files to include the new file into the build and remove it from the BUILD.gn files in the e2e folder.
7) Migrate the test file following the following instructions:

   - each test function should receive a 'devToolsPage' via its arguments and 'inspectedPage' if needed.
   - when calling helpers pass the 'devToolsPage' as the last argument.
   - update the helpers that are used by the test to accept 'devToolsPage' as the last argument if needed. CRITICAL: DO NOT UPDATE helpers if an equivalent already exists on the 'DevToolsPage'. Remember that $$, $, waitFor, click, hover, typeText helpers are available directly on devToolsPage. Rewrite accordingly.
   - keep the helpers from @test/e2e/helpers in place.
   - in helpers, the 'devToolsPage' argument should be the last one and it should be optional defaulting to 'getBrowserAndPagesWrappers().devToolsPage'.
   - use the globally available 'setup' function define experiments and flags for the test.
   - rewrite any beforeEach/afterEach hooks to be local helper functions called from the test directly.
   - instead of using 'devToolsPage.keyboard.press' use 'devToolsPage.keyboard.pressKey'.
   - instead of using global 'click' use 'devToolsPage.click'.

8) After you are done with changes, run 'npm run test -- -t StrictTypes <target_test_file>' to verify.
9) Delete the original test file.
10) Create a new branch `git checkout -b fixed-<issue_id>`.
11) Commit the changes with the message 'Migrate <original_test_file>'
12) Run 'git cl presubmit --upload'
13) Run 'git cl upload -a -s -d -f --hashtag=migration-ai -x <issue_id>' to upload the change.
14) Fix any lint issues. You may have to re-commit if files changed. When re-committing, amend the initial commit to preserve the commit message.

"""
