// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2026 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

@scope to (devtools-widget > *) {
  :scope {
    width: 100%;
    box-shadow: none;
    padding: var(--sys-size-8);
    background-color: var(--sys-color-surface);
    border-radius: var(--sys-shape-corner-medium);
  }

  .export-for-agents-dialog {
    width: var(--sys-size-33); /* 512px */
    max-width: 100%; /* deal with the dialog being squashed on smaller devices */
  }

  .export-for-agents-dialog header {
    margin-bottom: var(--sys-size-6);

    h1 {
      font: var(--sys-typescale-headline5);
      margin: 0;
      color: var(--sys-color-on-surface);
    }
  }

  .export-for-agents-dialog .state-selection {
    display: flex;
    gap: var(--sys-size-5);
    margin: var(--sys-size-7) 0;
  }

  .export-for-agents-dialog .state-selection label {
    display: flex;
    align-items: center;
    gap: var(--sys-size-2);
    cursor: pointer;
    font: var(--sys-typescale-body3-regular);

    input {
      /* Remove the margin on radio buttons so that the text and the
       * radio button are properly aligned vertically. */
      margin-bottom: 0;
    }
  }

  .export-for-agents-dialog textarea {
    width: 100%;
    min-height: var(--sys-size-30); /* 288px */
    max-height: var(--sys-size-34); /* 512px */
    resize: none;
    padding: var(--sys-size-5);
    box-sizing: border-box;
    font-family: var(--monospace-font-family);
    font-size: var(--monospace-font-size);
    background-color: var(--sys-color-surface5);
    color: var(--sys-color-on-surface);
    border-radius: var(--sys-shape-corner-small);
    border: none;
  }

  main {
    position: relative;
  }

  .prompt-loading {
    position: absolute;
    padding: var(--sys-size-5);
    display: flex;
    align-items: center;
    justify-content: flex-start;
    gap: var(--sys-size-5);
  }

  .export-for-agents-dialog .disclaimer {
    margin-top: var(--sys-size-5);
    font: var(--sys-typescale-body4-regular);
    color: var(--sys-color-on-surface-subtle);
  }

  .export-for-agents-dialog footer {
    display: flex;
    justify-content: flex-end;
    margin-top: var(--sys-size-6);
  }

  .export-for-agents-dialog .right-buttons {
    display: flex;
    gap: var(--sys-size-5);
  }
}

/*# sourceURL=${import.meta.resolve('././components/exportForAgentsDialog.css')} */`;