import '../../ui/legacy/legacy.js';
import * as Common from '../../core/common/common.js';
import * as EmulationModel from '../../models/emulation/emulation.js';
export declare class DeviceModeToolbar {
    #private;
    private model;
    private readonly showMediaInspectorSetting;
    private readonly showRulersSetting;
    private readonly deviceOutlineSetting;
    private readonly showDeviceScaleFactorSetting;
    private readonly showUserAgentTypeSetting;
    private autoAdjustScaleSetting;
    private readonly lastMode;
    private readonly emulatedDevicesList;
    private readonly persistenceSetting;
    private mainToolbar;
    private optionsToolbar;
    constructor(model: EmulationModel.DeviceModeModel.DeviceModeModel, showMediaInspectorSetting: Common.Settings.Setting<boolean>, showRulersSetting: Common.Settings.Setting<boolean>);
    private createEmptyToolbarElement;
    private createSizeInput;
    private createMainToolbar;
    private renderMainToolbar;
    private createOptionsToolbar;
    private getDevicePostureOptions;
    private onPostureChange;
    private currentDevicePosture;
    private getScaleOptions;
    private onScaleChange;
    private getDeviceScaleFactorOptions;
    private onDeviceScaleChange;
    private getUserAgentOptions;
    private onUAChange;
    private appendOptionsMenuItems;
    private reset;
    private emulateDevice;
    private switchToResponsive;
    private filterDevices;
    private standardDevices;
    private customDevices;
    private allDevices;
    private getDeviceModeOptions;
    private onDeviceChange;
    private deviceListChanged;
    private spanClicked;
    private modeMenuClicked;
    private getPrettyFitZoomPercentage;
    private getPrettyZoomPercentage;
    element(): Element;
    update(): void;
    restore(): void;
    private calculateItemWidth;
}
