import { type LitTemplate } from '../../ui/lit/lit.js';
export declare const buildPropertyDefinitionText: (property: string, value?: string) => LitTemplate;
export declare const buildPropertyName: (property: string) => LitTemplate;
export declare const buildPropertyValue: (property: string) => LitTemplate;
export declare const isFlexContainer: (computedStyles?: Map<string, string>) => boolean;
export declare const isBlockContainer: (computedStyles?: Map<string, string>) => boolean;
export declare const isInlineElement: (computedStyles?: Map<string, string>) => boolean;
export declare const isPossiblyReplacedElement: (nodeName?: string) => boolean;
export declare const isGridContainer: (computedStyles?: Map<string, string>) => boolean;
export declare const isGridLanesContainer: (computedStyles?: Map<string, string>) => boolean;
export declare const isMulticolContainer: (computedStyles?: Map<string, string>) => boolean;
