import '../../ui/components/adorners/adorners.js';
import '../../ui/components/buttons/buttons.js';
import * as SDK from '../../core/sdk/sdk.js';
import * as TextUtils from '../../core/text_utils/text_utils.js';
import * as Protocol from '../../generated/protocol.js';
import type * as Elements from '../../models/elements/elements.js';
import * as IssuesManager from '../../models/issues_manager/issues_manager.js';
import * as CodeMirror from '../../third_party/codemirror.next/codemirror.next.js';
import * as TextEditor from '../../ui/components/text_editor/text_editor.js';
import * as UI from '../../ui/legacy/legacy.js';
import type { DirectiveResult } from '../../ui/lit/lit.js';
declare const enum TagType {
    OPENING = "OPENING_TAG",
    CLOSING = "CLOSING_TAG"
}
interface OpeningTagContext {
    tagType: TagType.OPENING;
    canAddAttributes: boolean;
}
interface ClosingTagContext {
    tagType: TagType.CLOSING;
}
export type TagTypeContext = OpeningTagContext | ClosingTagContext;
export declare function isOpeningTag(context: TagTypeContext): context is OpeningTagContext;
export interface ViewInput {
    node: SDK.DOMModel.DOMNode | null;
    isClosingTag: boolean;
    expanded: boolean;
    isExpandable: boolean;
    isXMLMimeType: boolean;
    updateRecord: Elements.ElementUpdateRecord.ElementUpdateRecord | null;
    onHighlightSearchResults: () => void;
    onExpand: () => void;
    issues?: IssuesManager.Issue.Issue[];
    containerAdornerActive: boolean;
    flexAdornerActive: boolean;
    gridAdornerActive: boolean;
    popoverAdornerActive: boolean;
    interestAdornerActive: boolean;
    adProvenance?: Protocol.Network.AdProvenance;
    target?: SDK.Target.Target;
    adTooltipId: string;
    showContainerAdorner: boolean;
    containerType?: string;
    showFlexAdorner: boolean;
    showGridAdorner: boolean;
    showGridLanesAdorner: boolean;
    showMediaAdorner: boolean;
    showPopoverAdorner: boolean;
    showInterestAdorner: boolean;
    showTopLayerAdorner: boolean;
    isSubgrid: boolean;
    showViewSourceAdorner: boolean;
    showScrollAdorner: boolean;
    showScrollSnapAdorner: boolean;
    topLayerIndex: number;
    scrollSnapAdornerActive: boolean;
    onGutterClick: (e: Event) => void;
    onContainerAdornerClick: (e: Event) => void;
    onFlexAdornerClick: (e: Event) => void;
    onGridAdornerClick: (e: Event) => void;
    onMediaAdornerClick: (e: Event) => void;
    onPopoverAdornerClick: (e: Event) => void;
    onInterestAdornerClick: (e: Event) => void;
    onScrollSnapAdornerClick: (e: Event) => void;
    onTopLayerAdornerClick: (e: Event) => void;
    onViewSourceAdornerClick: () => void;
    onSlotAdornerClick: (e: Event) => void;
    showSlotAdorner: boolean;
    showCustomElementAdorner: boolean;
    onCustomElementAdornerClick: (e: Event) => void;
    slotName?: string;
    showStartingStyleAdorner: boolean;
    startingStyleAdornerActive: boolean;
    onStartingStyleAdornerClick: (e: Event) => void;
    isHovered: boolean;
    isSelected: boolean;
    canInspect: boolean;
    showAiButton: boolean;
    aiButtonTitle?: string;
    onAiButtonClick: (e: Event) => void;
    decorations: Decoration[];
    descendantDecorations: Decoration[];
    decorationsTooltip: string;
    indent: number;
    editorState: CodeMirror.EditorState | null;
    editorWidth: number | null;
}
export interface ViewOutput {
    contentElement?: HTMLElement;
    editorRef?: TextEditor.TextEditor.TextEditor;
}
export declare function adornerRef(): DirectiveResult;
export interface Decoration {
    title: string;
    color: string;
}
export declare function handleAdornerKeydown(cb: (event: Event) => void): (event: KeyboardEvent) => void;
export declare const DEFAULT_VIEW: (input: ViewInput, output: ViewOutput, target: HTMLElement) => void;
type View = typeof DEFAULT_VIEW;
export interface InitialEditState {
    attributeName?: string;
    isNewAttribute?: boolean;
    isProcessingInstruction?: boolean;
    isTextNode?: boolean;
    isEditAsHTML?: boolean;
    editAsHTMLCallback?: (success: boolean) => void;
}
export declare class ElementsTreeWidget extends UI.Widget.Widget {
    #private;
    static readonly INJECT: readonly [typeof IssuesManager.DOMIssuesManager.DOMIssuesManager];
    isClosingTag: boolean;
    isXMLMimeType: boolean;
    disableEdits: boolean;
    showAIButton: boolean;
    isDOMNodeSelected: boolean;
    initialEdit?: InitialEditState | null;
    onInitialEditCompleted?: () => void;
    expand?: () => void;
    collapse?: () => void;
    selectTreeElement?: (omitFocus?: boolean, selectedByUser?: boolean) => boolean | void;
    expandRecursively?: (maxDepth?: number) => Promise<void>;
    collapseChildren?: () => void;
    childCount?: () => number;
    closingTagElement?: () => Element | null;
    updateShadowRootDepth?: (depth: number) => void;
    computeLeftIndent?: number | (() => number);
    setChildrenListElementVisible?: (visible: boolean) => void;
    findStartTagWidget?: () => ElementsTreeWidget | null;
    selectDOMNode?: (node: SDK.DOMModel.DOMNode, selectedByUser?: boolean) => void;
    revealInTopLayer?: (node: SDK.DOMModel.DOMNode) => void;
    showContextMenu?: (event: Event, widget?: ElementsTreeWidget) => void;
    populateTreeElement?: () => Promise<void>;
    toggleHideElement?: (node: SDK.DOMModel.DOMNode) => Promise<void>;
    isToggledToHidden?: (node: SDK.DOMModel.DOMNode) => boolean;
    selectNodeAfterEdit?: (wasExpanded: boolean, error: string | null, newNode: SDK.DOMModel.DOMNode | null, moveDirection?: string) => void;
    runPendingUpdates?: () => void;
    focusOutline?: () => void;
    setMultilineEditing?: (multilineEditing: EditorHandles | null) => void;
    visibleWidth?: () => number;
    inClipboard: boolean;
    editing: EditorHandles | null;
    expandAllButtonElement: UI.TreeOutline.TreeElement | null;
    get updateRecord(): Elements.ElementUpdateRecord.ElementUpdateRecord | null;
    set updateRecord(updateRecord: Elements.ElementUpdateRecord.ElementUpdateRecord | null);
    get node(): SDK.DOMModel.DOMNode;
    set node(node: SDK.DOMModel.DOMNode);
    get expanded(): boolean;
    set expanded(expanded: boolean);
    get isExpandable(): boolean;
    set isExpandable(isExpandable: boolean);
    get selected(): boolean;
    set selected(selected: boolean);
    get searchQuery(): string | null;
    set searchQuery(query: string | null);
    get tagTypeContext(): TagTypeContext;
    get issues(): IssuesManager.Issue.Issue[];
    constructor(element?: HTMLElement, [domIssuesManager]?: UI.Widget.WidgetDependencies<typeof ElementsTreeWidget> | [undefined], view?: View);
    static visibleShadowRoots(node: SDK.DOMModel.DOMNode): SDK.DOMModel.DOMNode[];
    static canShowInlineText(node: SDK.DOMModel.DOMNode): boolean;
    static populateForcedPseudoStateItems(contextMenu: UI.ContextMenu.ContextMenu, node: SDK.DOMModel.DOMNode): void;
    animateOnDOMUpdate(): void;
    wasShown(): void;
    performUpdate(): void;
    highlightAttribute(attributeName: string): void;
    isDisplayContents(): boolean;
    get isEditing(): boolean;
    highlightSearchResults(searchQuery: string): void;
    hideSearchHighlights(): void;
    setInClipboard(inClipboard: boolean): void;
    get hovered(): boolean;
    set hovered(isHovered: boolean);
    expandedChildrenLimit(): number;
    setExpandedChildrenLimit(expandedChildrenLimit: number): void;
    onTopLayerIndexChanged(): void;
    onbind(): void;
    clearView(): void;
    onunbind(): void;
    onattach(): void;
    onpopulate(): Promise<void>;
    onexpand(): void;
    oncollapse(): void;
    onselect(selectedByUser?: boolean): boolean;
    onenter(): boolean;
    ondblclick(event: Event): boolean;
    hasEditableNode(): boolean;
    private insertInLastAttributePosition;
    private startEditingTarget;
    private revealHTMLInSources;
    private isAiButtonEnabled;
    startEditing(): boolean | undefined;
    startEditingProcessingInstructionValue(): boolean | undefined;
    addNewAttribute(): boolean;
    triggerEditAttribute(attributeName: string): boolean | undefined;
    startEditingAttribute(attribute: Element, elementForSelection: Element): boolean;
    startEditingTextNode(textNodeElement: Element): boolean;
    startEditingTagName(tagNameElement?: Element): boolean;
    private updateEditorHandles;
    private startEditingAsHTML;
    private attributeEditingCommitted;
    private tagNameEditingCommitted;
    private textNodeEditingCommitted;
    editingCancelled(_element: Element, _tagName: string | null): void;
    private distinctClosingTagElement;
    updateTitle(updateRecord?: Elements.ElementUpdateRecord.ElementUpdateRecord | null): void;
    updateDecorations(): void;
    remove(): Promise<void>;
    toggleEditAsHTML(callback?: ((arg0: boolean) => void), startEditing?: boolean): void;
    editAsHTML(): void;
    updateAdorners(): void;
}
export declare class ElementsTreeElement extends UI.TreeOutline.TreeElement {
    #private;
    widget: ElementsTreeWidget;
    widgetWrapper: HTMLElement;
    nodeInternal: SDK.DOMModel.DOMNode;
    get tagTypeContext(): TagTypeContext;
    constructor(node: SDK.DOMModel.DOMNode, isClosingTag?: boolean);
    highlightSearchResults(searchQuery: string): void;
    hideSearchHighlights(): void;
    copyStyles(): Promise<void>;
    setInClipboard(inClipboard: boolean): void;
    get isEditing(): boolean;
    expandedChildrenLimit(): number;
    setExpandedChildrenLimit(limit: number): void;
    highlightAttribute(name: string): void;
    startEditing(): boolean | undefined;
    startEditingAttribute(attribute: Element, elementForSelection: Element): boolean;
    startEditingTextNode(textNodeElement: Element): boolean;
    editAsHTML(): void;
    copyCSSPath(): void;
    copyJSPath(): void;
    copyXPath(): void;
    copyFullXPath(): void;
    hasEditableNode(): boolean;
    toggleEditAsHTML(callback?: ((arg0: boolean) => void), startEditing?: boolean): void;
    get expandAllButtonElement(): UI.TreeOutline.TreeElement | null;
    set expandAllButtonElement(element: UI.TreeOutline.TreeElement | null);
    node(): SDK.DOMModel.DOMNode;
    isClosingTag(): boolean;
    onattach(): void;
    onpopulate(): Promise<void>;
    expandRecursively(): Promise<void>;
    onexpand(): void;
    oncollapse(): void;
    select(omitFocus?: boolean, selectedByUser?: boolean): boolean;
    onselect(selectedByUser?: boolean): boolean;
    deselect(): void;
    ondelete(): boolean;
    onenter(): boolean;
    selectOnMouseDown(event: MouseEvent): void;
    ondblclick(event: Event): boolean;
    onbind(): void;
    onunbind(): void;
    static animateOnDOMUpdate(treeElement: ElementsTreeElement): void;
    static visibleShadowRoots(node: SDK.DOMModel.DOMNode): SDK.DOMModel.DOMNode[];
    static canShowInlineText(node: SDK.DOMModel.DOMNode): boolean;
    static populateForcedPseudoStateItems(contextMenu: UI.ContextMenu.ContextMenu, node: SDK.DOMModel.DOMNode): void;
    set hovered(isHovered: boolean);
    get hovered(): boolean;
    updateAdorners(): void;
    get updateComplete(): Promise<void>;
    requestUpdate(): void;
    updateTitle(updateRecord?: Elements.ElementUpdateRecord.ElementUpdateRecord | null): void;
    triggerEditAttribute(attributeName: string): boolean;
    editingCancelled(element: Element, tagName: string | null): void;
    updateDecorations(): void;
    remove(): Promise<void>;
    addNewAttribute(): boolean;
    startEditingTagName(tagNameElement?: Element): boolean;
    startEditingProcessingInstructionValue(): boolean | undefined;
    isDisplayContents(): boolean;
    performUpdate(): void;
}
export declare const InitialChildrenLimit = 500;
/**
 * A union of HTML4 and HTML5-Draft elements that explicitly
 * or implicitly (for HTML5) forbid the closing tag.
 **/
export declare const ForbiddenClosingTagElements: Set<string>;
/** These tags we do not allow editing their tag name. **/
export declare const EditTagBlocklist: Set<string>;
export declare function convertUnicodeCharsToHTMLEntities(text: string): {
    text: string;
    entityRanges: TextUtils.TextRange.SourceRange[];
};
export interface EditorHandles {
    commit: () => void;
    cancel: () => void;
    resize: () => void;
}
export {};
