// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/**
 * Copyright 2022 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.layers-widget {
  overflow: hidden;
  padding-left: 2px;
  background-color: var(--sys-color-cdt-base-container);
  border-bottom: 1px solid var(--sys-color-divider);
  margin-top: 0;
  padding-bottom: 2px;
}

.layers-widget > .layers-widget-title {
  font-weight: bold;
  margin: 8px 4px 6px;
}

/*# sourceURL=${import.meta.resolve('./layersWidget.css')} */`;