// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/**
 * Copyright 2022 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.layers-widget {
  overflow: hidden;
  padding-left: var(--sys-size-2);
  background-color: var(--sys-color-cdt-base-container);
  border-bottom: var(--sys-size-1) solid var(--sys-color-divider);
  margin-top: 0;
  padding-bottom: var(--sys-size-2);
}

.layers-widget > .layers-widget-title {
  font-weight: bold;
  margin: var(--sys-size-5) var(--sys-size-3) var(--sys-size-4);
}

/*# sourceURL=${import.meta.resolve('./layersWidget.css')} */`;