// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2025 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.filtered-list-widget-item > .filtered-ui-source-code-list-item {
  align-content: center;
  display: grid;
  gap: var(--sys-size-2);
  line-height: initial;
}

.filtered-ui-source-code-list-item.is-ignore-listed * {
  color: var(--sys-color-state-disabled);
}

.filtered-ui-source-code-title {
  overflow: hidden;
  text-overflow: ellipsis;
}

.filtered-ui-source-code-title:not(.search-mode) {
  font-weight: var(--ref-typeface-weight-bold);
}

.filtered-ui-source-code-subtitle {
  flex: none;
  overflow: hidden;
  text-overflow: ellipsis;
  color: var(--sys-color-on-surface-subtle);
  padding-left: var(--sys-size-3);
  display: flex;
  white-space: pre;
}

.filtered-ui-source-code-subtitle .first-part {
  flex-shrink: 1000;
  overflow: hidden;
  text-overflow: ellipsis;
}

/*# sourceURL=${import.meta.resolve('./filteredUISourceCodeListProvider.css')} */`;