// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2022 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.border-container {
  border-bottom: 1px solid var(--sys-color-divider);
  flex-shrink: 0;
}

.automatic-workspace-infobar {
  border-top: var(--sys-size-1) solid var(--sys-color-divider);
}

.automatic-file-system-nudge {
  flex-shrink: 0;
  font-style: italic;
  border-bottom: var(--sys-size-1) solid var(--sys-color-divider);
  padding: var(--sys-size-3);
  text-align: center;
  color: var(--sys-color-on-surface-subtle);
}

/*# sourceURL=${import.meta.resolve('./sourcesNavigator.css')} */`;