# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../../scripts/build/ninja/bundle.gni")
import("../../../../scripts/build/ninja/devtools_module.gni")
import("../../../../scripts/build/typescript/typescript.gni")

web_vitals_injected_sources = [
  "OnEachLayoutShift.ts",
  "web-vitals-injected.ts",
]

devtools_module("web-vitals-injected") {
  sources = web_vitals_injected_sources

  ts_deps = [
    "../../../third_party/web-vitals:bundle",
    "../../trace:bundle",
    "./spec:bundle",
  ]

  visibility = [
    ":*",
    "../:live-metrics",
  ]
}

bundle("bundled_library") {
  entrypoint = "web-vitals-injected.ts"
  output_file_location = "$target_gen_dir/web-vitals-injected.generated.js"
  bundle_all = true
  format = "iife"
  sourcemap = false
  deps = [
    ":web-vitals-injected_sources",
    "../../../third_party/web-vitals:bundle",
  ]

  data = [ output_file_location ]
  metadata = {
    grd_files = [ output_file_location ]
  }

  visibility = [
    ":*",
    "../:live-metrics",
  ]
}
