import * as Platform from '../core/platform/platform.js';
import * as SDK from '../core/sdk/sdk.js';
import * as Protocol from '../generated/protocol.js';
export declare const LOADER_ID: Protocol.Network.LoaderId;
export declare const MAIN_FRAME_ID: Protocol.Page.FrameId;
export declare const DOMAIN = "example.com";
export declare const SECURITY_ORIGIN = "https://example.com";
export declare const FRAME_URL: Platform.DevToolsPath.UrlString;
export declare const FRAME: {
    url: Platform.DevToolsPath.UrlString;
    loaderId: Protocol.Network.LoaderId;
    domainAndRegistry: string;
    securityOrigin: string;
    mimeType: string;
    secureContextType: Protocol.Page.SecureContextType;
    crossOriginIsolatedContextType: Protocol.Page.CrossOriginIsolatedContextType;
    gatedAPIFeatures: never[];
};
export declare function getEffectivePayload(id: Protocol.Page.FrameId, base: Omit<Protocol.Page.Frame, 'id'>, framePayload?: Partial<Protocol.Page.Frame>): Protocol.Page.Frame;
export declare function getMainFrame(target: SDK.Target.Target, framePayload?: Partial<Protocol.Page.Frame>): SDK.ResourceTreeModel.ResourceTreeFrame;
export declare function createResource(frame: SDK.ResourceTreeModel.ResourceTreeFrame, networkScriptUrl: Platform.DevToolsPath.UrlString, mimeType: string, content: string): SDK.Resource.Resource;
