// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2021 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

@scope to (devtools-widget > *) {
  :scope {
    flex: auto;
    display: flex;
  }

  .value-interpreter {
    border: var(--sys-size-1) solid var(--sys-color-divider);
    background-color: var(--sys-color-cdt-base-container);
    overflow: hidden;
    width: 400px;
  }

  .settings-toolbar {
    min-height: 26px;
    display: flex;
    flex-wrap: nowrap;
    justify-content: space-between;
    padding-left: var(--sys-size-3);
    padding-right: var(--sys-size-3);
    align-items: center;
  }

  .settings-toolbar-button {
    padding: 0;
    width: var(--sys-size-9);
    height: var(--sys-size-9);
    border: none;
    outline: none;
    background-color: transparent;
  }

  .settings-toolbar-button.active devtools-icon {
    color: var(--icon-toggled);
  }

  .divider {
    display: block;
    height: var(--sys-size-1);
    margin-bottom: var(--sys-size-6);
    background-color: var(--sys-color-divider);
  }
}

/*# sourceURL=${import.meta.resolve('./linearMemoryValueInterpreter.css')} */`;