// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2021 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

@scope to (devtools-widget > *) {
  :scope {
    flex: auto;
    display: flex;
    min-height: 20px;
  }

  .settings {
    display: flex;
    flex-wrap: wrap;
    margin: 0 12px 12px;
    gap: 15px 45px;
  }

  .value-types-selection {
    display: flex;
    flex-direction: column;
  }

  .group {
    font-weight: bold;
    margin-bottom: var(--sys-size-6);
  }
}

/*# sourceURL=${import.meta.resolve('./valueInterpreterSettings.css')} */`;