// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2021 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  flex: auto;
  display: flex;
}

.value-types {
  width: 100%;
  display: grid;
  grid-template-columns: auto auto 1fr;
  gap: var(--sys-size-3) var(--sys-size-11);
  min-height: var(--sys-size-11);
  overflow: hidden;
  padding: var(--sys-size-2) var(--sys-size-6);
  align-items: baseline;
  justify-content: start;
}

.value-type-cell {
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  min-height: var(--sys-size-11);
}

.value-type-value-with-link {
  display: flex;
  align-items: center;
}

.value-type-cell-no-mode {
  grid-column: 1 / 3;
}

.signed-divider {
  width: var(--sys-size-1);
  height: 15px;
  background-color: var(--sys-color-divider);
  margin: 0 var(--sys-size-3);
}

.selectable-text {
  user-select: text;
}

.selectable-text::selection {
  background-color: var(--sys-color-tonal-container);
  color: currentcolor;
}

/*# sourceURL=${import.meta.resolve('./valueInterpreterDisplay.css')} */`;