// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2016 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */
.report-field-name {
  flex-basis: 152px;
}

.manifest-view-header {
  min-width: 600px;
  flex-shrink: 0;
  flex-grow: 0;
}

.manifest-container {
  overflow: auto;
}

.inline-icon {
  width: 16px;
  height: 16px;
  margin-inline: var(--sys-size-3);

  &[name="check-circle"] {
    color: var(--icon-checkmark-green);
  }
}

.multiline-value {
  padding-top: var(--sys-size-5);
  white-space: normal;
}

select {
  margin: 4px;
}

.inline-button {
  vertical-align: sub;
}

/*# sourceURL=${import.meta.resolve('./appManifestView.css')} */`;