// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2016 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.report-row {
  display: flex;
  align-items: center;
  white-space: normal;

  &:has(.quota-override-error:empty) {
    margin: 0;
  }
}

.clear-site-data-checkboxes-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: var(--sys-size-5) var(--sys-size-10);
  align-items: start;
}

.clear-site-data-checkbox-column {
  display: grid;
  row-gap: var(--sys-size-5);

  > devtools-checkbox {
    margin-left: 0;
  }
}

.clear-selected-button-row {
  margin-top: var(--sys-size-7);
}

.link {
  margin-left: 10px;
  display: none;
}

.report-row:hover .link {
  display: inline;
}

.quota-override-editor-with-button {
  align-items: baseline;
  display: flex;
}

.quota-override-notification-editor {
  border: solid 1px var(--sys-color-neutral-outline);
  border-radius: 4px;
  display: flex;
  flex: auto;
  margin-right: 4px;
  max-width: 200px;
  min-width: 50px;
  min-height: 19px;
  padding-left: 4px;

  &:focus {
    border-color: var(--sys-color-state-focus-ring);
  }

  &:hover:not(:focus) {
    background-color: var(--sys-color-state-hover-on-subtle);
  }
}

.quota-override-error:not(:empty) {
  padding-top: 10px;
  color: var(--sys-color-error);
}

.usage-breakdown-row {
  min-width: fit-content;
}

.clear-storage-container {
  overflow: auto;
}

.clear-storage-header {
  min-width: 400px;
  /* Keep in sync with ui/legacy/checkboxTextLabel.css (12px input, 6px margins). */
  --nested-checkbox-indent: 24px;
}

.report-content-box {
  overflow: initial;
}

.include-third-party-cookies-row {
  margin-left: var(--nested-checkbox-indent);

  > devtools-checkbox {
    margin-left: 0;
  }
}

/*# sourceURL=${import.meta.resolve('./storageView.css')} */`;