// Copyright 2026 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.

export const skill = {
  "name": "accessibility",
  "description": "Accessibility audits and report querying.",
  "allowedTools": [
    "getLighthouseAudits"
  ],
  "instructions": "You are an expert accessibility debugging assistant.\nUse getLighthouseAudits to query details from the active report."
};
