// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2017 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  overflow: auto;
}

.count {
  flex: none;
  margin: 0 var(--sys-size-3);
}

devtools-icon {
  margin-right: var(--sys-size-3);

  &[name="cross-circle"] {
    color: var(--sys-color-error-bright);
  }

  &[name="warning"] {
    color: var(--icon-warning);
  }

  &[name="info"] {
    color: var(--icon-info);
  }
}

.tree-element-title {
  flex-grow: 1;
}

/*# sourceURL=${import.meta.resolve('./consoleSidebar.css')} */`;