import * as Common from '../common/common.js';
import type * as Enums from './UserMetricsEnums.js';
export declare class UserMetrics {
    sourcesPanelFileDebugged(mediaType?: string): void;
    sourcesPanelFileOpened(mediaType?: string): void;
    networkPanelResponsePreviewOpened(mediaType: string): void;
    actionTaken(action: Action): void;
    resendRequest(resourceType: ResendRequestType): void;
    keybindSetSettingChanged(keybindSet: string): void;
    keyboardShortcutFired(actionId: string): void;
    issuesPanelOpenedFrom(issueOpener: IssueOpener): void;
    issuesPanelIssueExpanded(issueExpandedCategory?: string): void;
    issuesPanelResourceOpened(issueCategory: string, type: string): void;
    issueCreated(code: string): void;
    experimentEnabledAtLaunch(experimentId: string): void;
    navigationSettingAtFirstTimelineLoad(state: TimelineNavigationSetting): void;
    experimentDisabledAtLaunch(experimentId: string): void;
    experimentChanged(experimentId: string, isEnabled: boolean): void;
    developerResourceLoaded(developerResourceLoaded: DeveloperResourceLoaded): void;
    developerResourceScheme(developerResourceScheme: DeveloperResourceScheme): void;
    language(language: Intl.UnicodeBCP47LocaleIdentifier): void;
    syncSetting(devtoolsSyncSettingEnabled: boolean): void;
    recordingToggled(value: RecordingToggled): void;
    recordingReplayFinished(value: RecordingReplayFinished): void;
    recordingReplayStarted(value: RecordingReplayStarted): void;
    lighthouseModeRun(type: LighthouseModeRun): void;
    lighthouseCategoryUsed(type: LighthouseCategoryUsed): void;
    swatchActivated(swatch: SwatchType): void;
    workspacesPopulated(wallClockTimeInMilliseconds: number): void;
    visualLoggingProcessingDone(timeInMilliseconds: number): void;
    freestylerQueryLength(numberOfCharacters: number): void;
    freestylerEvalResponseSize(bytes: number): void;
    builtInAiAvailability(availability: BuiltInAiAvailability): void;
    consoleInsightTeaserGenerated(timeInMilliseconds: number): void;
    consoleInsightTeaserGeneratedMedium(timeInMilliseconds: number): void;
    consoleInsightTeaserFirstChunkGenerated(timeInMilliseconds: number): void;
    consoleInsightTeaserFirstChunkGeneratedMedium(timeInMilliseconds: number): void;
    consoleInsightTeaserChunkToEndMedium(timeInMilliseconds: number): void;
    consoleInsightTeaserAbortedAfterFirstCharacter(timeInMilliseconds: number): void;
    consoleInsightTeaserAbortedBeforeFirstCharacter(timeInMilliseconds: number): void;
    consoleInsightLongTeaserGenerated(timeInMilliseconds: number): void;
    consoleInsightShortTeaserGenerated(timeInMilliseconds: number): void;
}
export type Action = Enums.Action;
export declare const Action: typeof Enums.Action;
export type PanelCodes = Enums.PanelCodes;
export declare const PanelCodes: typeof Enums.PanelCodes;
export type MediaTypes = Enums.MediaTypes;
export declare const MediaTypes: typeof Enums.MediaTypes;
export type KeybindSetSettings = Enums.KeybindSetSettings;
export declare const KeybindSetSettings: typeof Enums.KeybindSetSettings;
export type KeyboardShortcutAction = Enums.KeyboardShortcutAction;
export declare const KeyboardShortcutAction: typeof Enums.KeyboardShortcutAction;
export type IssueOpener = Enums.IssueOpener;
export declare const IssueOpener: typeof Enums.IssueOpener;
export type DevtoolsExperiments = Enums.DevtoolsExperiments;
export declare const DevtoolsExperiments: typeof Enums.DevtoolsExperiments;
export type IssueExpanded = Enums.IssueExpanded;
export declare const IssueExpanded: typeof Enums.IssueExpanded;
export type IssueResourceOpened = Enums.IssueResourceOpened;
export declare const IssueResourceOpened: typeof Enums.IssueResourceOpened;
export type IssueCreated = Enums.IssueCreated;
export declare const IssueCreated: typeof Enums.IssueCreated;
export type DeveloperResourceLoaded = Enums.DeveloperResourceLoaded;
export declare const DeveloperResourceLoaded: typeof Enums.DeveloperResourceLoaded;
export type DeveloperResourceScheme = Enums.DeveloperResourceScheme;
export declare const DeveloperResourceScheme: typeof Enums.DeveloperResourceScheme;
export type Language = Enums.Language;
export declare const Language: typeof Enums.Language;
export type SyncSetting = Enums.SyncSetting;
export declare const SyncSetting: typeof Enums.SyncSetting;
export type RecordingToggled = Enums.RecordingToggled;
export declare const RecordingToggled: typeof Enums.RecordingToggled;
export type RecordingAssertion = Enums.RecordingAssertion;
export declare const RecordingAssertion: typeof Enums.RecordingAssertion;
export type RecordingReplayFinished = Enums.RecordingReplayFinished;
export declare const RecordingReplayFinished: typeof Enums.RecordingReplayFinished;
export type RecordingReplaySpeed = Enums.RecordingReplaySpeed;
export declare const RecordingReplaySpeed: typeof Enums.RecordingReplaySpeed;
export type RecordingReplayStarted = Enums.RecordingReplayStarted;
export declare const RecordingReplayStarted: typeof Enums.RecordingReplayStarted;
export type RecordingEdited = Enums.RecordingEdited;
export declare const RecordingEdited: typeof Enums.RecordingEdited;
export type RecordingExported = Enums.RecordingExported;
export declare const RecordingExported: typeof Enums.RecordingExported;
export type RecordingCodeToggled = Enums.RecordingCodeToggled;
export declare const RecordingCodeToggled: typeof Enums.RecordingCodeToggled;
export type RecordingCopiedToClipboard = Enums.RecordingCopiedToClipboard;
export declare const RecordingCopiedToClipboard: typeof Enums.RecordingCopiedToClipboard;
export type ManifestSectionCodes = Enums.ManifestSectionCodes;
export declare const ManifestSectionCodes: typeof Enums.ManifestSectionCodes;
export type LighthouseModeRun = Enums.LighthouseModeRun;
export declare const LighthouseModeRun: typeof Enums.LighthouseModeRun;
export type LighthouseCategoryUsed = Enums.LighthouseCategoryUsed;
export declare const LighthouseCategoryUsed: typeof Enums.LighthouseCategoryUsed;
export type SwatchType = Enums.SwatchType;
export declare const SwatchType: typeof Enums.SwatchType;
export type BadgeType = Enums.BadgeType;
export declare const BadgeType: typeof Enums.BadgeType;
export type AnimationsPlaybackRate = Enums.AnimationsPlaybackRate;
export declare const AnimationsPlaybackRate: typeof Enums.AnimationsPlaybackRate;
export type TimelineNavigationSetting = Enums.TimelineNavigationSetting;
export declare const TimelineNavigationSetting: typeof Enums.TimelineNavigationSetting;
export type BuiltInAiAvailability = Enums.BuiltInAiAvailability;
export declare const BuiltInAiAvailability: typeof Enums.BuiltInAiAvailability;
export type ResendRequestType = Enums.ResendRequestType;
export declare const ResendRequestType: typeof Enums.ResendRequestType;
export declare function resendRequestType(resourceType: Common.ResourceType.ResourceType): ResendRequestType;
