// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2014 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

@scope to (devtools-widget > *) {
  .event-source-messages-view {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
  }

  .event-source-messages-view devtools-data-grid {
    flex: auto;
    border: none;
  }
}

/*# sourceURL=${import.meta.resolve('./eventSourceMessagesView.css')} */`;