// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2016 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.custom-headers-list {
  height: 272px;
  width: var(--sys-size-29);
  margin: 0 var(--sys-size-8);
}

.header {
  margin: var(--sys-size-5) var(--sys-size-5) var(--sys-size-5) var(--sys-size-8);
  padding-top: var(--sys-size-3);
  font: var(--sys-typescale-body2-medium);
  flex: none;
}

.custom-headers-header {
  padding: 2px;
}

.custom-headers-list-item {
  padding-left: 5px;
}

.editor-container {
  padding: 5px 0 0 5px;
}

.add-button {
  margin: var(--sys-size-6) auto var(--sys-size-8) var(--sys-size-8);
  align-items: flex-start;
}

/*# sourceURL=${import.meta.resolve('./networkManageCustomHeadersView.css')} */`;