// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2018 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */
@scope to (devtools-widget > *) {
  .html-preview-frame {
    box-shadow: var(--drop-shadow);
    /* We always want a white background, even in dark mode */
    background: var(--ref-palette-neutral100);
    color-scheme: light;
    flex-grow: 1;
    margin: 20px;
  }
}

/*# sourceURL=${import.meta.resolve('./requestHTMLView.css')} */`;