// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2014 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.request-cookies-view {
  overflow: auto;
  padding: 12px;
  height: 100%;
  background-color: var(--sys-color-cdt-base-container);
}

.request-cookies-view .request-cookies-title {
  font-size: 12px;
  font-weight: bold;
  margin-right: 30px;
  color: var(--sys-color-on-surface);
}

.request-cookies-view .cookie-line {
  margin-top: 6px;
  display: flex;
}

.request-cookies-view .cookies-panel-item {
  margin-top: 6px;
  margin-bottom: 16px;
  flex: none;
}

/*# sourceURL=${import.meta.resolve('./requestCookiesView.css')} */`;