// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2015 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.list {
  border: none !important; /* stylelint-disable-line declaration-no-important */
  border-top: 1px solid var(--sys-color-divider) !important; /* stylelint-disable-line declaration-no-important */
  display: flex;
  height: 100%;
}

.blocking-disabled {
  opacity: 80%;
}

.editor-container {
  padding: 0 4px;
}

.blocked-urls {
  overflow: hidden auto;
}

.no-blocked-urls > span {
  white-space: pre;
}

.blocked-url {
  display: flex;
  flex-direction: row;
  align-items: center;
  flex: auto;

  devtools-button {
    flex: none;
  }
}

.blocked-url-count {
  flex: none;
  padding-right: 9px;
}

.blocked-url-checkbox {
  margin-left: 8px;
  flex: none;
}

.blocked-url-checkbox:focus {
  outline: auto 5px -webkit-focus-ring-color;
}

.blocked-url-label {
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
  flex: auto;
  padding: 0 3px;
}

.blocked-url-edit-row {
  flex: none;
  display: flex;
  flex-direction: row;
  margin: 7px 5px 0;
  align-items: center;
}

.blocked-url-edit-value {
  user-select: none;
  flex: 1 1 0;
}

.blocked-url-edit-row input {
  width: 100%;
  text-align: inherit;
  height: 22px;
}

.conditions-selector {
  width: max-content;
  flex: none;
  margin: var(--sys-size-3);
}

[disabled] {
  opacity: 50%;
}

/*# sourceURL=${import.meta.resolve('./requestConditionsDrawer.css')} */`;