// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/perf_ui/PieChart2.ts
*/

import './PieChart2.js';
/**
* @typedef {{
* value:number,
* color:string,
* title:string,
* }}
*/
// @ts-ignore we export this for Closure not TS
export let Slice;
// eslint-disable-next-line no-unused-vars
export class PieChart2ClosureInterface extends HTMLElement {
  /**
  * @param {{chartName: string, size: number, formatter: function(number): string, showLegend: boolean, total: number, slices: !Array.<!Slice>}} data
  */
  set data(data) {
  }
}
/**
* @return {!PieChart2ClosureInterface}
*/
export function createPieChart2() {
  return /** @type {!PieChart2ClosureInterface} */ (document.createElement('devtools-perf-piechart'));
}
