// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2016 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.layers-3d-view {
  overflow: hidden;
  user-select: none;

  > .empty-view-scroller{
    inset: 0;
    position: absolute;
    background-color: var(--sys-color-cdt-base-container);
  }
}

devtools-toolbar {
  background-color: var(--sys-color-cdt-base-container);
  border-bottom: 1px solid var(--sys-color-divider);
}

canvas {
  flex: 1 1;
}

.layers-3d-view > canvas:focus-visible {
  outline: auto 5px -webkit-focus-ring-color;
}

/*# sourceURL=${import.meta.resolve('./layers3DView.css')} */`;