// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2021 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.container {
  width: 100%;
  display: inline-block;
}

.container:hover {
  background-color: var(--sys-color-state-hover-on-subtle);
}

span {
  color: var(--sys-color-token-meta);
  font-family: var(--monospace-font-family);
  font-size: var(--monospace-font-size);
}

.role-value {
  color: var(--sys-color-token-tag);
}

.attribute-name {
  color: var(--sys-color-token-attribute);
}

.attribute-value {
  color: var(--sys-color-token-attribute-value);
}

/*# sourceURL=${import.meta.resolve('./accessibilityTreeNode.css')} */`;