// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `/*
 * Copyright 2022 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.hint-popup-wrapper {
  max-width: 232px;
}

code {
  font-weight: bold;
  font-family: inherit;
}

.hint-popup-possible-fix {
  margin-top: 8px;
}

.clickable {
  color: var(--sys-color-primary);
}

.underlined {
  text-decoration: underline;
}

.unbreakable-text {
  white-space: nowrap;
}

.footer {
  margin-top: var(--sys-size-5);
}

/*# sourceURL=${import.meta.resolve('./cssHintDetailsView.css')} */`;