# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../scripts/build/ninja/devtools_module.gni")
import("../../../scripts/build/typescript/typescript.gni")

devtools_foundation_module("protocol_client") {
  split_compilation = true
  sources = [
    "CDPConnection.ts",
    "ConnectionTransport.ts",
    "DevToolsCDPConnection.ts",
    "InspectorBackend.ts",
  ]

  ts_deps = [
    "../../generated",
    "../../generated:protocol",
    "../platform:bundle",
  ]
}

# TODO: We keep PuppeteerDevToolsConnection in a separate target because node
# types will leak into the rest of DevTools compilation otherwise!
devtools_foundation_module("puppeteer_devtools_connection") {
  split_compilation = true
  sources = [ "PuppeteerDevToolsConnection.ts" ]

  ts_deps = [
    ":protocol_client",
    "../../third_party/puppeteer:bundle",
  ]
}

devtools_entrypoint("bundle") {
  split_compilation = true
  entrypoint = "protocol_client.ts"

  ts_deps = [ ":protocol_client" ]

  visibility = [ "*" ]
}

devtools_foundation_module("unittests") {
  testonly = true
  split_compilation = true

  sources = [
    "InspectorBackend.test.ts",
    "PuppeteerDevToolsConnection.test.ts",
  ]

  ts_deps = [
    ":bundle",
    ":puppeteer_devtools_connection",
    "../../generated:protocol",
    "../../testing",
    "../../third_party/puppeteer:bundle",
  ]
}
