name: Build DevTools frontend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GCLIENT_ROOT: $RUNNER_TEMP/gclient_root
    steps:
    - name: Cache CIPD
      uses: actions/cache@v3
      with:
        path: .cipd
        key: ${{ runner.os }}-cipd
    - uses: actions/checkout@v3
    - name: setup-depot-tools
      uses: newkdev/setup-depot-tools@v1.0.1
    - name: Cache gclient workspace
      uses: actions/cache@v3
      with:
        path: |
          $GCLIENT_ROOT
          !$GCLIENT_ROOT/devtools-frontend
        key: ${{ runner.os }}-gclient-workspace-${{ hashFiles('DEPS') }}
        restore-keys: |
          ${{ runner.os }}-gclient-workspace
    - name: Sync gclient workspace
      run: |
        CURRENT_CHECKOUT_DIR="$(pwd)"
        mkdir -p $GCLIENT_ROOT
        cd $GCLIENT_ROOT
        gclient config --unmanaged "$CURRENT_CHECKOUT_DIR" --name devtools-frontend
        gclient sync --no-history
    - name: Build DevTools frontend
      run: |
        cd $GCLIENT_ROOT/devtools-frontend
        gn gen out/Default
        autoninja -C out/Default
    - uses: actions/upload-artifact@v3
      with:
        name: dist-front_end
        path: $GCLIENT_ROOT/devtools-frontend/out/Default/gen/front_end
    