name: Build DevTools frontend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache CIPD
      uses: actions/cache@v3
      with:
        path: src/.cipd
        key: ${{ runner.os }}-cipd
    - uses: actions/checkout@v3
      with:
        path: src
    - name: setup-depot-tools
      uses: newkdev/setup-depot-tools@v1.0.1
    - name: Cache gclient workspace
      uses: actions/cache@v3
      with:
        path: |
          .
          !src
          !!src/out
        key: ${{ runner.os }}-gclient-workspace-${{ hashFiles('src/DEPS') }}
        restore-keys: |
          ${{ runner.os }}-gclient-workspace
    - name: Sync gclient workspace
      run: |
        gclient config --unmanaged src --name src
        gclient sync --no-history
    - name: Build DevTools frontend
      run: |
        cd src
        gn gen out/Default
        autoninja -C out/Default
    - uses: actions/upload-artifact@v3
      with:
        name: dist-front_end
        path: src/out/Default/gen/front_end
    