name: Build and deploy DevTools frontend

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: dist-front_end
        path: $RUNNER_TEMP/dist-front_end
    - name: Deploy DevTools frontend
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: $RUNNER_TEMP/dist-front_end
