name: publish-on-tag

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          TAG_NAME: ${{github.ref_name}}
        run: |
          rm .npmrc
          npm version --no-git-tag-version $TAG_NAME
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          npm publish --provenance --access public
